name: .NET CI

on:
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ct/ct.sln
      - name: Test Order2020IsChronological
        run: dotnet test ct/ct.sln --no-build --filter FullyQualifiedName=ct.tests.ByBitTests.Order2020IsChronological
      - name: Test Order2022IsChronological
        run: dotnet test ct/ct.sln --no-build --filter FullyQualifiedName=ct.tests.ByBitTests.Order2022IsChronological
      - name: Test Order2025IsChronological
        run: dotnet test ct/ct.sln --no-build --filter FullyQualifiedName=ct.tests.ByBitTests.Order2025IsChronological
      - name: Test Volume2020Matches
        run: dotnet test ct/ct.sln --no-build --filter FullyQualifiedName=ct.tests.ByBitTests.Volume2020Matches
      - name: Test Volume2022Matches
        run: dotnet test ct/ct.sln --no-build --filter FullyQualifiedName=ct.tests.ByBitTests.Volume2022Matches
      - name: Test Volume2025Matches
        run: dotnet test ct/ct.sln --no-build --filter FullyQualifiedName=ct.tests.ByBitTests.Volume2025Matches
