name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ct/ct.sln
      - name: Build
        run: dotnet build ct/ct.sln --configuration Release --no-restore
      - name: Run tests
        run: dotnet run --project ct/ct.tests/ct.tests.csproj --configuration Release
